### ISSUE TITLE
Support label / value for select tag

### ISSUE THREAD

**Issue by KajloBro** [bobf/active_element#9]
https://github.com/bobf/active_element/blob/main/app/assets/javascripts/active_element/json_field.js#L419

Currently, it looks like `label` is supported `Option` attribute, but it doesn't seem to be working.

.yml example:
```
---
type: object
shape:
  fields:
  - name: dummy
    type: string
    options:
    - label: label1
      value: value1
    - label: label2
      value: value2
```

Expected output:
```
<select...>
  <option value="value1">label1</option>
  <option value="value2">label2</option>
</select>
```
